### ISSUE TITLE
【nitpicking】一部の文言の表記ゆれや漢字→ひらがなへの修正について

### ISSUE THREAD

**Issue by statditto** [mochikoAsTech/technical-writing-book#8]
- 殆ど→ほとんど
- 「伝える」と「つたえる」の表記ゆれ
この二点が少しだけ気になりましたがそれほど重要ではないかもしれません。特に後者は過去の書籍でひらがなを用いた表現を利用しているようだったのでこのままでも問題ない可能性があると思います。

**Comment by mochikoAsTech** [comment]
ありがとうございます！

ひらがなで統一しました。
https://github.com/mochikoAsTech/technical-writing-book/commit/46070e880ab59c1fdb0cf1bc65671d3512cba63e
```
  - expected: ほとんど
    pattern:  殆ど
   - expected: つたえる
    pattern:  伝える
```
