### ISSUE TITLE
【Nice-to-have】きれいな階層構造の作り方について

### ISSUE THREAD

**Issue by statditto** [mochikoAsTech/technical-writing-book#9]
想定する読者層に、

> どこに何が書いてあるのか一目で分かるような階層構造を作りたい人

との記載がありましたが、本文中ではあまり触れられていなかった気がします。もう少し記載があると（主に僕が）うれしいです！

**Comment by mochikoAsTech** [comment]
たしかに～！これ、当初がっつり書こうと思ってたんですが、全然間に合わなかったので削ったものなのでした。改訂第2版にご期待ください。
表紙および想定読者層から「きれいな階層構造の作り方が載ってそう！」と期待させる文言を外します。
https://github.com/mochikoAsTech/technical-writing-book/commit/f1eebeecdd6ddd170806e225313032078c526bab
